config/routes.rb
Splitr::Application.routes.draw do
  resource :user, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :budgets do
    resources :members, only: %i[new create destroy]
    resources :transactions, only: %i[new create edit update destroy]
  end
  root to: "welcome#index"
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  has_many :members,      dependent: :destroy
  has_many :money_transactions, dependent: :destroy

  validates :name, presence: true
  validates :precision, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  def total
    money_transactions.sum(:amount)
  end

  def total_for_member(member)
    member_id = member.try(:id) || member
    member_transactions = money_transactions.joins(:participations).where(participations: {member_id: member_id})
    owed = member_transactions.to_a.sum { |transaction| Rational(transaction.amount.to_r, transaction.participants.count) }
    paid = -money_transactions.where(payer_id: member_id).sum(:amount).to_r
    paid + owed
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  def index
    authorize! :read, Budget
    @budgets = current_user.budgets
  end

  def new
    @budget = Budget.new
    authorize! :create, @budget
  end

  def create
    @budget = Budget.new(budget_params)
    authorize! :create, @budget
    if BudgetCreator.create(@budget, current_user)
      redirect_to budgets_path, notice: "Budget has been successfully created."
    else
      render :new
    end
  end

  def show
    authorize! :read, Budget
    @budget = current_user.budgets.find(params[:id])
  end

  def edit
    authorize! :update, Budget
    @budget = current_user.budgets.find(params[:id])
  end

  def update
    authorize! :update, Budget
    @budget = current_user.budgets.find(params[:id])
    if @budget.update(budget_params)
      redirect_to budgets_path, notice: "Budget has been successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, Budget
    @budget = current_user.budgets.find(params[:id])
    @budget.destroy
    redirect_to budgets_path, notice: "Budget has been successfully removed."
  end

  private

  def budget_params
    params.require(:budget).permit(:name, :currency, :precision, :separator, :delimiter, :format, :negative_format)
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
  def transaction_participants(transaction)
    transaction.participants.pluck(:name).to_sentence
  end

  def budget_number_to_currency(budget, number)
    options = {
      precision: budget.precision,
      unit: budget.currency,
      separator: budget.separator,
      delimiter: budget.delimiter,
      format: budget.format,
      negative_format: budget.negative_format
    }

    number_to_currency(number, options.select { |key, value| value.present? })
  end
end

app/views/budgets/_form.html.erb
<fieldset>

  <legend>Budget</legend>

  <div class="form-group <%= 'has-error' if @budget.errors[:name].present? %>">
    <%= form.label :name, class: "control-label col-lg-2" %>
    <div class="col-lg-10">
      <%= form.text_field :name, class: "form-control" %>
      <span class="help-block"><%= @budget.errors[:name].first %></span>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @budget.errors[:currency].present? %>">
    <%= form.label :currency, class: "control-label col-lg-2" %>
    <div class="col-lg-10">
      <div class="row">
        <div class="col-lg-2">
          <%= form.text_field :currency, class: "form-control" %>
        </div>
      </div>
      <span class="help-block"><%= @budget.errors[:currency].first %></span>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-10 col-offset-2">
      <button type="button" class="btn btn-default" data-toggle="collapse" data-target=".advanced">Advanced Settings</button>
    </div>
  </div>

  <div class="advanced collapse">

    <div class="form-group <%= 'has-error' if @budget.errors[:precision].present? %>">
      <%= form.label :precision, class: "control-label col-lg-2" %>
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-2">
            <%= form.number_field :precision, class: "form-control", value: @budget.precision || 2, min: 0, step: 1 %>
          </div>
        </div>
        <span class="help-block">Number of decimal places (default: 2)</span>
        <span class="help-block"><%= @budget.errors[:precision].first %></span>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @budget.errors[:separator].present? %>">
      <%= form.label :separator, class: "control-label col-lg-2" %>
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-2">
            <%= form.text_field :separator, class: "form-control" %>
          </div>
        </div>
        <span class="help-block">Separator between dollars and cents (default: <code>.</code>)</span>
        <span class="help-block"><%= @budget.errors[:separator].first %></span>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @budget.errors[:delimiter].present? %>">
      <%= form.label :delimiter, class: "control-label col-lg-2" %>
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-2">
            <%= form.text_field :delimiter, class: "form-control" %>
          </div>
        </div>
        <span class="help-block">Delimiter between thousands (default: <code>,</code>)</span>
        <span class="help-block"><%= @budget.errors[:delimiter].first %></span>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @budget.errors[:format].present? %>">
      <%= form.label :format, class: "control-label col-lg-2" %>
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-2">
            <%= form.text_field :format, class: "form-control" %>
          </div>
        </div>
        <span class="help-block">Format for non-negative numbers (default: <code>%u%n</code>). Fields are <code>%u</code> for the currency, and <code>%n</code> for the number.</span>
        <span class="help-block"><%= @budget.errors[:format].first %></span>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @budget.errors[:negative_format].present? %>">
      <%= form.label :negative_format, class: "control-label col-lg-2" %>
      <div class="col-lg-10">
        <div class="row">
          <div class="col-lg-2">
            <%= form.text_field :negative_format, class: "form-control" %>
          </div>
        </div>
        <span class="help-block">Format for negative numbers (default: prepending an hyphen to the formatted number given by format). Fields are <code>%u</code> for the currency, and <code>%n</code> for the absolute value of number.</span>
        <span class="help-block"><%= @budget.errors[:negative_format].first %></span>
      </div>
    </div>

  </div>

</fieldset>

app/views/budgets/edit.html.erb
<div class="container">

  <%= form_for @budget, html: {class: "form-horizontal"} do |form| %>

    <%= render "form", form: form %>

    <div class="form-group">
      <div class="col-lg-10 col-offset-2">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/budgets/index.html.erb
<div class="container">
  <h4>
    Your budgets
  </h4>

  <table class="table table-hover">
    <tr>
      <th>Name</th>
      <th class="text-center">Members</th>
      <th class="text-right">Total Amount</th>
      <th class="text-right">
        <% if can? :create, Budget %>
          <%= link_to "", new_budget_path, class: "btn btn-success btn-small glyphicon glyphicon-plus" %>
        <% end %>
      </th>
    </tr>
    <% @budgets.order(created_at: :desc).each do |budget| %>
      <tr>
        <td><%= budget.name %></td>
        <td class="text-center"><%= budget.members.count %></td>
        <td class="text-right <%= amount_class(budget.total) %>"><%= budget_number_to_currency(budget, budget.total) %></td>
        <td class="text-right">
          <%= link_to "", budget_path(budget), class: "btn btn-primary btn-small glyphicon glyphicon-eye-open" %>
          <% if can? :manage, Budget %>
            <%= link_to "", edit_budget_path(budget), class: "btn btn-primary btn-small glyphicon glyphicon-pencil" %>
            <%= link_to "", budget_path(budget), class: "btn btn-danger btn-small glyphicon glyphicon-remove", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/budgets/new.html.erb
<div class="container">

  <%= form_for @budget, html: {class: "form-horizontal"} do |form| %>

    <%= render "form", form: form %>

    <div class="form-group">
      <div class="col-lg-10 col-offset-2">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/budgets/show.html.erb
<div class="container">
  <h4>
    <%= @budget.name %> Transactions
  </h4>

  <table class="table table-hover">
    <tr>
      <th>Issued on</th>
      <th>Description</th>
      <th>Payer</th>
      <th>Participants</th>
      <th class="text-right">Amount</th>
      <th class="text-right">
        <% if can? :manage, @budget %>
          <%= link_to "", new_budget_transaction_path(@budget), class: "btn btn-success btn-small glyphicon glyphicon-plus" %>
        <% end %>
      </th>
    </tr>
    <% @budget.money_transactions.order(issued_on: :desc).each do |transaction| %>
      <tr class="<%= amount_class(transaction.amount) %>">
        <td><%= transaction.issued_on.to_s(:db) %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.payer_name %></td>
        <td><%= transaction_participants(transaction) %></td>
        <td class="text-right"><%= budget_number_to_currency(@budget, transaction.amount) %></td>
        <td class="text-right">
          <% if can? :manage, Budget %>
            <%= link_to "", edit_budget_transaction_path(@budget, transaction), class: "btn btn-primary btn-small glyphicon glyphicon-pencil" %>
            <%= link_to "", budget_transaction_path(@budget, transaction), class: "btn btn-danger btn-small glyphicon glyphicon-remove", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr class="<%= amount_class(@budget.total) %>">
      <th colspan="5" class="text-right"><%= budget_number_to_currency(@budget, @budget.total) %></th>
      <th></th>
    </tr>
  </table>

  <h4>
    Members
  </h4>

  <table class="table table-hover">
    <tr>
      <th>Name</th>
      <th class="text-right">Total</th>
      <th class="text-right">
        <% if can? :manage, @budget %>
          <%= link_to "", new_budget_member_path(@budget), class: "btn btn-success btn-small glyphicon glyphicon-plus" %>
        <% end %>
      </th>
    </tr>
    <% @budget.members.order(:name).each do |member| %>
      <% @budget.total_for_member(member).tap do |total| %>
        <tr class="<%= amount_class(total) %>">
          <td><%= member.name %></td>
          <td class="text-right"><%= budget_number_to_currency(@budget, total) %></td>
          <td class="text-right">
            <% if can? :manage, @budget %>
              <%= link_to "", budget_member_path(@budget, member), class: "btn btn-danger btn-small glyphicon glyphicon-remove", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>