config/routes.rb
Splitr::Application.routes.draw do
  resource :user, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :budgets do
    resources :members, only: %i[new create destroy]
    resources :transactions, only: %i[new create edit update destroy]
  end
  root to: "welcome#index"
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :budget
  belongs_to :payer, class_name: "Member"
  has_many :participations, inverse_of: :transaction, dependent: :destroy
  has_many :participants, through: :participations, source: :member

  validates :budget,       presence: true
  validates :description,  presence: true
  validates :issued_on,    presence: true
  validates :amount,       presence: true, numericality: {allow_nil: true, other_than: 0}
  validates :participants, presence: true
  validate :payer_belongs_to_budget, if: :payer_id?

  def payer_belongs_to_budget
    errors.add :payer_id, :invalid unless budget.members.include?(payer)
  end

  def payer_name
    payer.try(:name).presence or "None"
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    authorize! :manage, Budget
    @transaction = budget.money_transactions.build
  end

  def create
    authorize! :manage, Budget

    @transaction = budget.money_transactions.build(transaction_params)
    if @transaction.save
      redirect_to budget_path(budget), notice: "Transaction has been successfully added."
    else
      render :new
    end
  end

  def edit
    authorize! :manage, Budget
    @transaction = budget.money_transactions.find(params[:id])
  end

  def update
    authorize! :manage, Budget
    @transaction = budget.money_transactions.find(params[:id])
    if @transaction.update(transaction_params)
      redirect_to budget_path(budget), notice: "Transaction has been successfully updated."
    else
      render :edit
    end
  end

  def destroy
    authorize! :manage, Budget
    @transaction = budget.money_transactions.find(params[:id])
    @transaction.destroy
    redirect_to budget_path(budget), notice: "Transaction has been successfully destroyed."
  end

  private

  def budget
    @budget ||= current_user.budgets.find(params[:budget_id])
  end

  def transaction_params
    params.require(:money_transaction).permit(:description, :issued_on, :amount, :payer_id, participant_ids: [])
  end
end

app/views/transactions/_form.html.erb
<fieldset>

  <legend>Transaction</legend>

  <div class="form-group <%= 'has-error' if @transaction.errors[:amount].present? %>">
    <%= form.label :amount, class: "control-label col-lg-2" %>
    <div class="col-lg-10">
      <%= form.number_field :amount, class: "form-control", value: @transaction.amount, step: "any" %>
      <span class="help-block"><%= @transaction.errors[:amount].first %></span>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @transaction.errors[:description].present? %>">
    <%= form.label :description, class: "control-label col-lg-2" %>
    <div class="col-lg-10">
      <%= form.text_field :description, class: "form-control" %>
      <span class="help-block"><%= @transaction.errors[:description].first %></span>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @transaction.errors[:issued_on].present? %>">
    <%= form.label :issued_on, class: "control-label col-lg-2" %>
    <div class="col-lg-10">
      <%# Change "value" to symbol on Rails 4.0.1 https://github.com/rails/rails/commit/53eb9fdd9c546b101b22e1711ed0c3dd3df19197 %>
      <%= form.date_field :issued_on, "value" => @transaction.issued_on || Date.current.to_s, class: "form-control" %>
      <span class="help-block"><%= @transaction.errors[:issued_on].first %></span>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @transaction.errors[:payer_id].present? %>">
    <%= form.label :payer_id, class: "control-label col-lg-2" %>
    <div class="col-lg-10">
      <%= form.select :payer_id, options_from_collection_for_select(@transaction.budget.members, "id", "name", @transaction.payer_id), {include_blank: "None"}, class: "form-control" %>
      <span class="help-block"><%= @transaction.errors[:payer_id].first %></span>
    </div>
  </div>

  <div class="form-group <%= 'has-error' if @transaction.errors[:participants].present? %>">
    <%= form.label :participants, class: "control-label col-lg-2" %>
    <div class="col-lg-10">
      <a id="js-transaction-participants-toggle" class="btn btn-default" href="javascript:void(0)" data-all="All" data-none="None">All</a>
      <% @budget.members.each do |member| %>
        <div id="js-transaction-participants" class="checkbox">
          <label>
            <%= check_box_tag "money_transaction[participant_ids][]", member.id, @transaction.participant_ids.include?(member.id) %>
            <%= member.name %>
          </label>
        </div>
      <% end %>
    </div>
    <span class="help-block col-lg-10 col-offset-2"><%= @transaction.errors[:participants].first %></span>
  </div>

</fieldset>

app/views/transactions/edit.html.erb
<div class="container">
  <%= form_for [@budget, @transaction], url: budget_transaction_path(@budget, @transaction), html: {class: "form-horizontal"} do |form| %>

    <%= render "form", form: form %>

    <div class="form-group">
      <div class="col-lg-10 col-offset-2">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>

app/views/transactions/new.html.erb
<div class="container">
  <%= form_for [@budget, @transaction], url: budget_transactions_path(@budget), html: {class: "form-horizontal"} do |form| %>

    <%= render "form", form: form %>

    <div class="form-group">
      <div class="col-lg-10 col-offset-2">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>
</div>