config/routes.rb
Splitr::Application.routes.draw do
  resource :user, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :budgets do
    resources :members, only: %i[new create destroy]
    resources :transactions, only: %i[new create edit update destroy]
  end
  root to: "welcome#index"
end

app/views/layouts/_flash.html.erb
<div class="container">
  <% if flash[:notice].present? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:alert].present? %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <% if flash[:error].present? %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% end %>
</div>

app/views/layouts/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to "Splitr", root_path, class: "navbar-brand" %>

    <div class="nav-collapse navbar-responsive-collapse collapse">
      <ul class="nav navbar-nav ">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <% if can? :create, User %>
          <li class="<%= 'active' if current_page?(new_user_path) %>"><%= link_to "Register", new_user_path %></li>
        <% end %>
        <% if can? :create, Session %>
          <li class="<%= 'active' if current_page?(new_session_path) %>"><%= link_to "Log in", new_session_path %></li>
        <% end %>
        <% if can? :read, Budget %>
          <li class="<%= 'active' if current_page?(budgets_path) %>"><%= link_to "Budgets", budgets_path %></li>
        <% end %>
        <% if can? :destroy, Session %>
          <li class="<%= 'active' if current_page?(session_path) %>"><%= link_to "Log out", session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Splitr</title>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

</head>
<body>

<div class="wrap">

<%= render "layouts/menu" %>
<%= render "layouts/flash" if flash.present? %>

<%= yield %>

<div class="push"></div>

</div>

<div class="footer">
  <div class="container">
    <p class="muted">
      &copy; 2013 <a href="http://cowbell-labs.com">Cowbell Labs</a>.
      View source on <a href="https://github.com/cowbell/splitr">GitHub</a>.
    </p>
  </div>
</div>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

</body>
</html>